#include<stdio.h>
#include<stdlib.h>
#include<time.h>
int displayscores(int msc,int psc)
{
	printf("\n machinescore \t playerscore ");
	printf("\n %d    \t\t\t  %d",msc,psc);
}
int main()
{
	int num,guess,i,psc,msc;
	char choice,player;
	printf("Welcome to random number guess game\n");
      do{
	srand(time(NULL));
	num = rand()%10;
	printf("enter player name:");
	scanf("%s",&player);
	printf("guess the number generated by the computer between 0 to 9:\n");
	for(i=3;i>=1;i--)
	{
		scanf("%d",&guess);
		if(num == guess)
		 break;
		else
		 printf("oops,you missed the number,you have %d more chances to guess\n",i-1);
       if(i==0){
         msc++;
         printf("machine gets a point");
        }
       else{
        psc++;
        printf("%s wins a point",player);
        }
       displayscores(msc,psc);  
       printf("\ndo you want to continue the game(Y/N)?");		
		scanf("%c",&choice);
	}
}
       while(choice == 'y'|| 'Y');
      if(msc<psc)
       printf("congratulations %s,you won the game");
      else if(msc>psc)
       printf("\n machine wins");
     else
       printf("Game draw");
    
return 0;
}
